server:
  port: 8084

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
logging:
  level:
    com.example.bro-messenger.security: info

